import M1 from "./images/project_EEB/M.jpg";
import M2 from "./images/project_Hotel/M2.jpg";
import M3 from "./images/project_Chat/M3.jpg";

export const profile = {
  name: "Nguyen Tien Phat",
  role: "Full-stack Developer",
  location: "Ho Chi Minh City, Vietnam",
  email: "phatnguyen03022001@gmail.com",
  github: "https://github.com/phatnguyen03022001",
  linkedin: "https://www.linkedin.com/in/phatnguyen03022001/",
  intro: "I build useful, reliable web applications with React, Node.js and modern web technologies.",
  currentFocus: "Web applications that are simple to use and easy to maintain.",
};

export const experience = [
  {
    title: "Software Engineering Intern",
    company: "MiuTech Company",
    period: "04 — 06 / 2024",
    description: "Worked on real-world web development tasks and applied full-stack skills in a team environment.",
  },
];

export const education = [
  {
    title: "Software Engineering",
    school: "Ton Duc Thang University",
    period: "2019 — 2024",
    description: "Built a foundation in software engineering through coursework and practical software projects.",
  },
];

export const principles = [
  { title: "Understand first", description: "Start with the problem and the people using the product." },
  { title: "Keep it clear", description: "Prefer small, understandable solutions over unnecessary complexity." },
  { title: "Keep improving", description: "Review, test and improve the work instead of treating the first version as final." },
];

export const projects = [
  {
    title: "English Exam Bank",
    slug: "english-exam-bank",
    year: "2024",
    role: "Full-stack Developer",
    tag: "Graduation Project",
    summary: "An exam management platform for students, teachers and education managers.",
    problem: "The project focused on giving teachers a simple way to create exams, manage questions and review student results.",
    solution: "I built the main frontend and backend flows for exam creation, question management, user roles and result tracking.",
    challenge: "The project brought several user roles and exam workflows into one application, so the main challenge was keeping those flows clear and connected.",
    tradeoff: "MongoDB kept question and exam data flexible, while React and Express kept the frontend and API structure familiar and easy to work with.",
    outcome: "A working full-stack project with a live demo, source code and a clear set of exam-management flows.",
    decisions: [
      "React for a clear and reusable user interface.",
      "Node.js and Express for the API layer.",
      "MongoDB for flexible question and exam data.",
    ],
    evidence: ["Source code", "Live demo", "Project screenshots"],
    stack: ["React", "Node.js", "Express", "MongoDB"],
    image: M1,
    github: "https://github.com/phatnguyen03022001/ExamBankEnglish",
    demo: "https://englishexambank.vercel.app/",
  },
  {
    title: "Hotel Management",
    slug: "hotel-management",
    year: "2023",
    role: "Full-stack Developer",
    tag: "Final Project",
    summary: "A hotel management system designed for administrators and guests.",
    problem: "The project focused on connecting hotel operations with a simple guest booking experience.",
    solution: "I worked on the web application, including guest flows, management screens and database integration.",
    challenge: "The application had to connect guest-facing actions with structured hotel data and management screens without adding unnecessary complexity.",
    tradeoff: "MySQL was chosen for structured hotel and booking data, while server-rendered views kept the application simple for its scope.",
    outcome: "A working web application with guest and management flows, a live deployment and source code.",
    decisions: [
      "Express and Node.js for the application server.",
      "MySQL for structured hotel and booking data.",
      "Server-rendered views for a simple and focused application.",
    ],
    evidence: ["Source code", "Live demo", "Project screenshots"],
    stack: ["Node.js", "Express", "EJS", "MySQL"],
    image: M2,
    github: "https://github.com/phatnguyen03022001/hotel",
    demo: "https://hotel-management-system-fytd.onrender.com/",
  },
  {
    title: "RealChat",
    slug: "real-chat",
    year: "2024",
    role: "Solo Developer",
    tag: "Realtime Project",
    summary: "A small real-time chat application built with Socket.io.",
    problem: "The goal was to understand how real-time messages move between users without refreshing the page.",
    solution: "I built a focused chat application around a Node.js server and Socket.io events.",
    challenge: "The core challenge was keeping the real-time event flow simple enough to understand while still giving users immediate message updates.",
    tradeoff: "The project stayed intentionally small so the real-time communication flow could remain easy to inspect and learn from.",
    outcome: "A focused real-time chat demo that shows the message flow without requiring page refreshes.",
    decisions: [
      "Socket.io for real-time communication.",
      "Node.js and Express for the server.",
      "A small scope to keep the real-time flow easy to understand.",
    ],
    evidence: ["Source code", "Live demo", "Project screenshots"],
    stack: ["Node.js", "Express", "Socket.io"],
    image: M3,
    github: "https://github.com/phatnguyen03022001/ChatAppSocket",
    demo: "https://chatappsocket-y9ya.onrender.com/",
  },
  {
    title: "Muse Portfolio",
    slug: "muse-portfolio",
    year: "2026",
    role: "Full-stack Developer",
    tag: "Product Portfolio",
    summary: "A photography-first model portfolio with public content, project inquiries and an owner-only admin.",
    problem: "The project needed a polished portfolio experience that could keep public content simple while still supporting managed content and inquiries.",
    solution: "I built the public Home and Contact experience plus an owner-only admin backed by PostgreSQL, Better Auth, Cloudinary and Resend.",
    challenge: "The challenge was balancing editorial presentation with production concerns such as authentication, content management, media handling and inquiry delivery.",
    tradeoff: "The system keeps design rules and layout system-owned while making content mutable through the admin, which reduces accidental design drift.",
    outcome: "A reusable, responsive portfolio product with public pages, managed content, inquiry handling and documented production architecture.",
    decisions: [
      "Next.js App Router for the public and owner experiences.",
      "PostgreSQL for managed content and application state.",
      "Better Auth, Cloudinary and Resend for owner and media workflows.",
    ],
    evidence: ["Source code", "Production reference", "Project documentation"],
    stack: ["Next.js", "React", "TypeScript", "Tailwind CSS", "PostgreSQL"],
    image: "https://opengraph.githubassets.com/1/phatnguyen03022001/muse-portfolio",
    github: "https://github.com/phatnguyen03022001/muse-portfolio",
    demo: "https://muse-portfolio-seven.vercel.app/",
  },
  {
    title: "Elite Drive",
    slug: "elite-drive",
    year: "2026",
    role: "Full-stack Developer",
    tag: "Full-stack Marketplace",
    summary: "A premium car-rental marketplace connecting renters, vehicle owners and platform administrators.",
    problem: "The product needed one operational system for vehicle discovery, booking, KYC, fleet management, trip handover and platform operations.",
    solution: "I worked across the Next.js frontend and NestJS API, connecting role-specific workflows through Prisma, MongoDB and authenticated API routes.",
    challenge: "The application spans three operational roles and multiple stateful workflows, so clear boundaries and consistent validation were essential.",
    tradeoff: "The payment flow remains an explicit sandbox adapter until a production provider and signed webhook layer are connected.",
    outcome: "A portfolio-grade marketplace with renter, owner and admin workflows, CI coverage and a production deployment.",
    decisions: [
      "Next.js and NestJS for a clear frontend/API boundary.",
      "Prisma and MongoDB for application data and role workflows.",
      "Explicit sandbox payment boundaries instead of presenting incomplete production payments as finished.",
    ],
    evidence: ["Source code", "Production demo", "Architecture documentation"],
    stack: ["Next.js", "React", "NestJS", "Prisma", "MongoDB"],
    image: "https://opengraph.githubassets.com/1/phatnguyen03022001/elite-drive-demo-version",
    github: "https://github.com/phatnguyen03022001/elite-drive-demo-version",
    demo: "https://elite-drive-iota.vercel.app/",
  },
  {
    title: "Spackie Question",
    slug: "spackie-question",
    year: "2025",
    role: "Full-stack Developer",
    tag: "Realtime Chat API",
    summary: "A Next.js chat application API with role management, realtime updates and view-once image messages.",
    problem: "The project focused on building a compact chat system with secure sessions, realtime events and different admin/user responsibilities.",
    solution: "I built API routes and supporting application flows for auth, rooms, messages, user search, image uploads, admin monitoring and realtime events through Pusher.",
    challenge: "The difficult part was keeping message state, room state and realtime events consistent while supporting view-once image behavior.",
    tradeoff: "The application stays intentionally focused on the chat domain rather than expanding into a broader social platform.",
    outcome: "A complete chat application API with documented routes, shadcn-style UI foundations and realtime message flows.",
    decisions: [
      "Next.js App Router for the full-stack application boundary.",
      "MongoDB with Mongoose for chat and user data.",
      "Pusher for realtime events and Cloudinary for image storage.",
    ],
    evidence: ["Source code", "API documentation", "Design documentation"],
    stack: ["Next.js", "React", "MongoDB", "Pusher", "Cloudinary"],
    image: "https://opengraph.githubassets.com/1/phatnguyen03022001/spackie-question",
    github: "https://github.com/phatnguyen03022001/spackie-question",
  },
];

export const skills = ["React", "Node.js", "Express", "JavaScript", "MongoDB", "MySQL", "Tailwind CSS", "Docker"];
